<font size="7"><span style="color: #33D6CC;">LIMPIEZA DE LOS DATOS</span></font>


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import re
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv('tenis_bruto.csv')
df

C:\Users\albam\AppData\Local\Temp\ipykernel_25728\584941035.py:1: DtypeWarning: Columns (8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('tenis_bruto.csv')


tourney_id                  tourney_name  \
0                              1968-2029                        Dublin   
1                              1968-2029                        Dublin   
2                              1968-2029                        Dublin   
3                              1968-2029                        Dublin   
4                              1968-2029                        Dublin   
...                                  ...                           ...   
193332  2024-M-DC-2024-WG2-PO-URU-MDA-01  Davis Cup WG2 PO: URU vs MDA   
193333  2024-M-DC-2024-WG2-PO-VIE-RSA-01  Davis Cup WG2 PO: VIE vs RSA   
193334  2024-M-DC-2024-WG2-PO-VIE-RSA-01  Davis Cup WG2 PO: VIE vs RSA   
193335  2024-M-DC-2024-WG2-PO-VIE-RSA-01  Davis Cup WG2 PO: VIE vs RSA   
193336  2024-M-DC-2024-WG2-PO-VIE-RSA-01  Davis Cup WG2 PO: VIE vs RSA   

       surface  draw_size tourney_level  tourney_date  match_num  winner_id  \
0        Grass       32.0             A      19680708        270     112411   
1        Grass       32.0             A      19680708        271     126914   
2        Grass       32.0             A      19680708        272     209523   
3        Grass       32.0             A      19680708        273     100084   
4        Grass       32.0             A      19680708        274     100132   
...        ...        ...           ...           ...        ...        ...   
193332    Clay        4.0             D      20240203          5     212051   
193333    Hard        4.0             D      20240202          1     122533   
193334    Hard        4.0             D      20240202          2     144748   
193335    Hard        4.0             D      20240202          4     122533   
193336    Hard        4.0             D      20240202          5     202475   

       winner_seed winner_entry  ... l_1stIn l_1stWon  l_2ndWon l_SvGms  \
0              NaN          NaN  ...     NaN      NaN       NaN     NaN   
1              NaN          NaN  ...     NaN      NaN       NaN     NaN   
2              NaN          NaN  ...     NaN      NaN       NaN     NaN   
3              NaN          NaN  ...     NaN      NaN       NaN     NaN   
4              NaN          NaN  ...     NaN      NaN       NaN     NaN   
...            ...          ...  ...     ...      ...       ...     ...   
193332         NaN          NaN  ...    30.0     17.0       7.0     6.0   
193333         NaN          NaN  ...    41.0     25.0       6.0     9.0   
193334         NaN          NaN  ...    51.0     25.0       7.0    11.0   
193335         NaN          NaN  ...    51.0     32.0      17.0    14.0   
193336         NaN          NaN  ...    53.0     25.0       8.0     8.0   

        l_bpSaved  l_bpFaced winner_rank winner_rank_points loser_rank  \
0             NaN        NaN         NaN                NaN        NaN   
1             NaN        NaN         NaN                NaN        NaN   
2             NaN        NaN         NaN                NaN        NaN   
3             NaN        NaN         NaN                NaN        NaN   
4             NaN        NaN         NaN                NaN        NaN   
...           ...        ...         ...                ...        ...   
193332        8.0       14.0      1109.0                8.0      740.0   
193333        1.0        4.0       554.0               67.0      748.0   
193334        5.0       12.0       416.0              109.0        NaN   
193335        5.0        9.0       554.0               67.0      416.0   
193336        9.0       14.0       748.0               32.0        NaN   

       loser_rank_points  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
...                  ...  
193332              34.0  
193333              32.0  
193334               NaN  
193335             109.0  
193336               NaN  

[193337 rows x 49 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193337 entries, 0 to 193336
Data columns (total 49 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   tourney_id          193337 non-null  object 
 1   tourney_name        193337 non-null  object 
 2   surface             190347 non-null  object 
 3   draw_size           192502 non-null  float64
 4   tourney_level       193337 non-null  object 
 5   tourney_date        193337 non-null  int64  
 6   match_num           193337 non-null  int64  
 7   winner_id           193337 non-null  int64  
 8   winner_seed         71544 non-null   object 
 9   winner_entry        16943 non-null   object 
 10  winner_name         193337 non-null  object 
 11  winner_hand         193327 non-null  object 
 12  winner_ht           176236 non-null  float64
 13  winner_ioc          193329 non-null  object 
 14  winner_age          192026 non-null  float64
 15  loser_id            193337 non-nul

# GENÉRICA 

In [349]:
df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')

In [350]:
df.isnull().mean()*100

tourney_id             0.000000
tourney_name           0.000000
surface                1.546522
draw_size              0.431888
tourney_level          0.000000
tourney_date           0.000000
match_num              0.000000
winner_id              0.000000
winner_seed           62.995185
winner_entry          91.236546
winner_name            0.000000
winner_hand            0.005172
winner_ht              8.845177
winner_ioc             0.004138
winner_age             0.678091
loser_id               0.000000
loser_seed            81.133461
loser_entry           85.141489
loser_name             0.000000
loser_hand             0.025344
loser_ht              15.468327
loser_ioc              0.037241
loser_age              2.408747
score                  0.004655
best_of                0.000000
round                  0.000000
minutes               51.544712
w_ace                 50.116636
w_df                  50.117153
w_svpt                50.117153
w_1stIn               50.117153
w_1stWon

In [351]:
    # Eliminación de columnas sin valor
columnas=['tourney_id','match_num','winner_seed','winner_entry','loser_seed','loser_entry']
df.drop(columns=columnas,inplace= True)
df.head(5)

tourney_name surface  draw_size tourney_level  tourney_date  winner_id  \
0       Dublin   Grass       32.0             A      19680708     112411   
1       Dublin   Grass       32.0             A      19680708     126914   
2       Dublin   Grass       32.0             A      19680708     209523   
3       Dublin   Grass       32.0             A      19680708     100084   
4       Dublin   Grass       32.0             A      19680708     100132   

       winner_name winner_hand  winner_ht winner_ioc  ...  l_1stIn  l_1stWon  \
0       Doug Smith           U        NaN        AUS  ...      NaN       NaN   
1  Louis Pretorius           R        NaN        RSA  ...      NaN       NaN   
2     Cecil Pedlow           U        NaN        IRL  ...      NaN       NaN   
3        Tom Okker           R      178.0        NED  ...      NaN       NaN   
4  Armistead Neely           R        NaN        USA  ...      NaN       NaN   

  l_2ndWon l_SvGms  l_bpSaved l_bpFaced  winner_rank winner_rank_points  \
0      NaN     NaN        NaN       NaN          NaN                NaN   
1      NaN     NaN        NaN       NaN          NaN                NaN   
2      NaN     NaN        NaN       NaN          NaN                NaN   
3      NaN     NaN        NaN       NaN          NaN                NaN   
4      NaN     NaN        NaN       NaN          NaN                NaN   

   loser_rank loser_rank_points  
0         NaN               NaN  
1         NaN               NaN  
2         NaN               NaN  
3         NaN               NaN  
4         NaN               NaN  

[5 rows x 43 columns]

In [352]:
df.isnull().mean()*100

tourney_name           0.000000
surface                1.546522
draw_size              0.431888
tourney_level          0.000000
tourney_date           0.000000
winner_id              0.000000
winner_name            0.000000
winner_hand            0.005172
winner_ht              8.845177
winner_ioc             0.004138
winner_age             0.678091
loser_id               0.000000
loser_name             0.000000
loser_hand             0.025344
loser_ht              15.468327
loser_ioc              0.037241
loser_age              2.408747
score                  0.004655
best_of                0.000000
round                  0.000000
minutes               51.544712
w_ace                 50.116636
w_df                  50.117153
w_svpt                50.117153
w_1stIn               50.117153
w_1stWon              50.117153
w_2ndWon              50.117153
w_SvGms               50.116636
w_bpSaved             50.117153
w_bpFaced             50.117153
l_ace                 50.117153
l_df    

In [353]:
df.shape

(193337, 43)

In [354]:
    #quitar filas con minutes nulos
df = df.dropna(subset=['minutes'])
df.shape

(93682, 43)

In [355]:
    # NEXTGEN mecanismo del torneo diferente 
df = df[~df['tourney_name'].str.startswith('NextGen', na=False)]
df.shape

(93591, 43)

In [356]:
   # Eliminar los partidos walkover y retirados
df = df[df['score']!='W/O']
df = df[df['score']!=' W/O']
df = df[df['score']!=' RET']
df.shape

(93532, 43)

In [357]:
    # eliminar partidos de retirados,walkover o descalificados en score
df = df[~df['score'].str.contains('RET', na=False)]
df = df[~df['score'].str.contains('DEF', na=False)]
df = df[~df['score'].str.contains('Def.', na=False)]
df[df['score'].str.contains(' W/O', na=False)]['score']
df.shape

(91006, 43)

In [358]:
    #eliminar partidos con menos sets de los que hay que ganar según best_of
#variable sets por partido
sets=[]
for i in df.score:
     sets.append(len(i.split()))
   
df['sets']=sets
#eliminacion de los que se han jugado 2 y es al mejor de 5
df = df[~((df['sets']==2) & (df['best_of']==5))]
df.shape

(91005, 44)

In [363]:
    # eliminar outliers en minutos>350
df = df.query('minutes<350')
df.shape

(89212, 44)

In [364]:
    # eliminar los partidos de menos de 25 minutos excepto el de shangai que si es real
fila = df[(df['minutes']==25.0) & (df['tourney_name']=='Shanghai')]
df = df[df['minutes']>25.0]
df = pd.concat([df, fila], ignore_index=True)
df.shape

(89206, 44)

In [359]:
 # cambiar las filas con Carpet a partir de 2009 por Hard
df['tourney_date'] = df['tourney_date'].astype(str)
df.loc[(df['surface'] == 'Carpet') & (df['tourney_date'].str.startswith('2009')), 'surface'] = 'Hard'
df['tourney_date'] = df['tourney_date'].astype(int)

In [361]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              3
winner_ht              537
winner_ioc               0
winner_age               1
loser_id                 0
loser_name               0
loser_hand              24
loser_ht              1459
loser_ioc                0
loser_age               19
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   19
w_df                    20
w_svpt                  20
w_1stIn                 20
w_1stWon                20
w_2ndWon                20
w_SvGms                 20
w_bpSaved               20
w_bpFaced               20
l_ace                   20
l_df                    19
l_svpt                  20
l_1stIn                 20
l_1stWon                20
l_2ndWon                20
l_SvGms                 20
l

In [362]:
    # eliminamos los nulos de esas columnas por no poder asignarles valor (visto en numéricas)
df = df.dropna(subset=['winner_rank','winner_rank_points','loser_rank','loser_rank_points'])
df.shape

(89219, 44)

In [365]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              0
winner_ht              463
winner_ioc               0
winner_age               0
loser_id                 0
loser_name               0
loser_hand               5
loser_ht              1231
loser_ioc                0
loser_age                7
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l

In [366]:
df.columns

Index(['tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date',
       'winner_id', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc',
       'winner_age', 'loser_id', 'loser_name', 'loser_hand', 'loser_ht',
       'loser_ioc', 'loser_age', 'score', 'best_of', 'round', 'minutes',
       'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms',
       'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn',
       'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points',
       'sets'],
      dtype='object')

# NUMÉRICAS

In [367]:
    # DF de variables numéricas
df_num = df._get_numeric_data()
df_num

draw_size  tourney_date  winner_id  winner_ht  winner_age  loser_id  \
0           32.0      19910107     101142      180.0        25.6    101746   
1           32.0      19910107     101613      180.0        21.5    100587   
2           32.0      19910107     101179      185.0        25.3    101601   
3           32.0      19910107     101117      180.0        25.8    101332   
4           32.0      19910107     101901      185.0        19.7    101735   
...          ...           ...        ...        ...         ...       ...   
89201        4.0      20240203     105430      175.0        34.2    212051   
89202        4.0      20240203     105430      175.0        34.2    208364   
89203        4.0      20240203     212051        NaN        18.8    209943   
89204        4.0      20240202     122533        NaN        26.9    202475   
89205        4.0      20240202     122533        NaN        26.9    144748   

       loser_ht  loser_age  best_of  minutes  ...  l_1stWon  l_2ndWon  \
0         175.0       20.6        3     63.0  ...      17.0       7.0   
1         188.0       31.8        3     72.0  ...      22.0       6.0   
2         185.0       21.6        3    101.0  ...      24.0      14.0   
3         173.0       23.8        3    108.0  ...      38.0      15.0   
4         196.0       20.6        3     65.0  ...      21.0      12.0   
...         ...        ...      ...      ...  ...       ...       ...   
89201       NaN       18.8        3     81.0  ...      13.0       6.0   
89202     185.0       23.9        3     95.0  ...      33.0       6.0   
89203       NaN       21.8        3     77.0  ...      17.0       7.0   
89204       NaN       23.2        3    131.0  ...      25.0       6.0   
89205       NaN       27.3        3    159.0  ...      32.0      17.0   

       l_SvGms  l_bpSaved  l_bpFaced  winner_rank  winner_rank_points  \
0          8.0        2.0        6.0          9.0              1487.0   
1          8.0        7.0       11.0         94.0               371.0   
2         11.0        4.0        8.0         77.0               468.0   
3         13.0        8.0       12.0         65.0               502.0   
4          9.0        4.0        6.0        190.0               142.0   
...        ...        ...        ...          ...                 ...   
89201      8.0        0.0        6.0        136.0               489.0   
89202      8.0        6.0       11.0        136.0               489.0   
89203      6.0        8.0       14.0       1109.0                 8.0   
89204      9.0        1.0        4.0        554.0                67.0   
89205     14.0        5.0        9.0        554.0                67.0   

       loser_rank  loser_rank_points  sets  
0            78.0              459.0     2  
1           220.0              114.0     2  
2           212.0              116.0     3  
3            72.0              483.0     3  
4            28.0              876.0     2  
...           ...                ...   ...  
89201      1109.0                8.0     2  
89202       616.0               55.0     2  
89203       740.0               34.0     2  
89204       748.0               32.0     2  
89205       416.0              109.0     3  

[89206 rows x 33 columns]

In [368]:
df_num.describe()

draw_size  tourney_date      winner_id     winner_ht    winner_age  \
count  89206.000000  8.920600e+04   89206.000000  88743.000000  89206.000000   
mean      57.353429  2.006554e+07  107596.367699    185.832809     25.914112   
std       36.810125  9.673286e+04   17804.476225      6.652298      3.794761   
min        2.000000  1.991011e+07  100284.000000    168.000000     15.800000   
25%       32.000000  1.998062e+07  102202.000000    183.000000     23.100000   
50%       32.000000  2.006061e+07  103720.000000    185.000000     25.600000   
75%       64.000000  2.015012e+07  104918.000000    190.000000     28.400000   
max      128.000000  2.024052e+07  212051.000000    211.000000     42.300000   

            loser_id      loser_ht     loser_age       best_of       minutes  \
count   89206.000000  87975.000000  89199.000000  89206.000000  89206.000000   
mean   107494.733291    185.267928     26.066929      3.331278    105.489261   
std     17542.079521      6.607985      3.879360      0.743517     38.751093   
min    100282.000000    160.000000     15.400000      3.000000     26.000000   
25%    102202.000000    180.000000     23.200000      3.000000     76.000000   
50%    103602.000000    185.000000     25.800000      3.000000     98.000000   
75%    104926.000000    190.000000     28.600000      3.000000    127.000000   
max    212203.000000    211.000000     44.000000      5.000000    345.000000   

       ...      l_1stWon     l_2ndWon       l_SvGms     l_bpSaved  \
count  ...  89190.000000  89190.00000  89190.000000  89190.000000   
mean   ...     32.124700     15.05412     12.275188      4.825395   
std    ...     14.058613      7.07757      3.992722      3.256168   
min    ...      0.000000      0.00000      0.000000     -6.000000   
25%    ...     22.000000     10.00000      9.000000      2.000000   
50%    ...     30.000000     14.00000     11.000000      4.000000   
75%    ...     40.000000     19.00000     15.000000      7.000000   
max    ...    145.000000     66.00000     41.000000     27.000000   

          l_bpFaced   winner_rank  winner_rank_points    loser_rank  \
count  89190.000000  89206.000000        89206.000000  89206.000000   
mean       8.753414     63.368910         1492.328633     98.753044   
std        4.083305     81.640095         1774.401095    128.656639   
min        0.000000      1.000000            1.000000      1.000000   
25%        6.000000     17.000000          574.000000     36.000000   
50%        8.000000     44.000000          915.000000     68.000000   
75%       11.000000     82.000000         1665.000000    111.000000   
max       38.000000   1890.000000        16950.000000   2159.000000   

       loser_rank_points          sets  
count       89206.000000  89206.000000  
mean          926.588279      2.577697  
std          1009.267268      0.737696  
min             1.000000      2.000000  
25%           427.000000      2.000000  
50%           681.000000      2.000000  
75%          1055.000000      3.000000  
max         16950.000000      5.000000  

[8 rows x 33 columns]

In [369]:
df_num.isnull().sum()

draw_size                0
tourney_date             0
winner_id                0
winner_ht              463
winner_age               0
loser_id                 0
loser_ht              1231
loser_age                7
best_of                  0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l_bpSaved               16
l_bpFaced               16
winner_rank              0
winner_rank_points       0
loser_rank               0
loser_rank_points        0
sets                     0
dtype: int64

In [370]:
    #imputar NaN con la media en : winner_ht,winner_age,loser_ht,loser_age 
columns=['winner_ht','winner_age','loser_ht','loser_age']

imputer = SimpleImputer (missing_values=np.nan, strategy="mean")

df_num[columns] = imputer.fit_transform(df_num[columns])

df_num

draw_size  tourney_date  winner_id   winner_ht  winner_age  loser_id  \
0           32.0      19910107     101142  180.000000        25.6    101746   
1           32.0      19910107     101613  180.000000        21.5    100587   
2           32.0      19910107     101179  185.000000        25.3    101601   
3           32.0      19910107     101117  180.000000        25.8    101332   
4           32.0      19910107     101901  185.000000        19.7    101735   
...          ...           ...        ...         ...         ...       ...   
89201        4.0      20240203     105430  175.000000        34.2    212051   
89202        4.0      20240203     105430  175.000000        34.2    208364   
89203        4.0      20240203     212051  185.832809        18.8    209943   
89204        4.0      20240202     122533  185.832809        26.9    202475   
89205        4.0      20240202     122533  185.832809        26.9    144748   

         loser_ht  loser_age  best_of  minutes  ...  l_1stWon  l_2ndWon  \
0      175.000000       20.6        3     63.0  ...      17.0       7.0   
1      188.000000       31.8        3     72.0  ...      22.0       6.0   
2      185.000000       21.6        3    101.0  ...      24.0      14.0   
3      173.000000       23.8        3    108.0  ...      38.0      15.0   
4      196.000000       20.6        3     65.0  ...      21.0      12.0   
...           ...        ...      ...      ...  ...       ...       ...   
89201  185.267928       18.8        3     81.0  ...      13.0       6.0   
89202  185.000000       23.9        3     95.0  ...      33.0       6.0   
89203  185.267928       21.8        3     77.0  ...      17.0       7.0   
89204  185.267928       23.2        3    131.0  ...      25.0       6.0   
89205  185.267928       27.3        3    159.0  ...      32.0      17.0   

       l_SvGms  l_bpSaved  l_bpFaced  winner_rank  winner_rank_points  \
0          8.0        2.0        6.0          9.0              1487.0   
1          8.0        7.0       11.0         94.0               371.0   
2         11.0        4.0        8.0         77.0               468.0   
3         13.0        8.0       12.0         65.0               502.0   
4          9.0        4.0        6.0        190.0               142.0   
...        ...        ...        ...          ...                 ...   
89201      8.0        0.0        6.0        136.0               489.0   
89202      8.0        6.0       11.0        136.0               489.0   
89203      6.0        8.0       14.0       1109.0                 8.0   
89204      9.0        1.0        4.0        554.0                67.0   
89205     14.0        5.0        9.0        554.0                67.0   

       loser_rank  loser_rank_points  sets  
0            78.0              459.0     2  
1           220.0              114.0     2  
2           212.0              116.0     3  
3            72.0              483.0     3  
4            28.0              876.0     2  
...           ...                ...   ...  
89201      1109.0                8.0     2  
89202       616.0               55.0     2  
89203       740.0               34.0     2  
89204       748.0               32.0     2  
89205       416.0              109.0     3  

[89206 rows x 33 columns]

In [371]:
df.isnull().sum()

tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
winner_id                0
winner_name              0
winner_hand              0
winner_ht              463
winner_ioc               0
winner_age               0
loser_id                 0
loser_name               0
loser_hand               5
loser_ht              1231
loser_ioc                0
loser_age                7
score                    0
best_of                  0
round                    0
minutes                  0
w_ace                   16
w_df                    16
w_svpt                  16
w_1stIn                 16
w_1stWon                16
w_2ndWon                16
w_SvGms                 16
w_bpSaved               16
w_bpFaced               16
l_ace                   16
l_df                    16
l_svpt                  16
l_1stIn                 16
l_1stWon                16
l_2ndWon                16
l_SvGms                 16
l

In [372]:
    #imputar NaN con el más frecuente en: w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
columns=['w_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved','w_bpFaced',
         'l_ace','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced']

imputer = SimpleImputer (missing_values=np.nan, strategy="most_frequent")

df_num[columns] = imputer.fit_transform(df_num[columns])

df_num

draw_size  tourney_date  winner_id   winner_ht  winner_age  loser_id  \
0           32.0      19910107     101142  180.000000        25.6    101746   
1           32.0      19910107     101613  180.000000        21.5    100587   
2           32.0      19910107     101179  185.000000        25.3    101601   
3           32.0      19910107     101117  180.000000        25.8    101332   
4           32.0      19910107     101901  185.000000        19.7    101735   
...          ...           ...        ...         ...         ...       ...   
89201        4.0      20240203     105430  175.000000        34.2    212051   
89202        4.0      20240203     105430  175.000000        34.2    208364   
89203        4.0      20240203     212051  185.832809        18.8    209943   
89204        4.0      20240202     122533  185.832809        26.9    202475   
89205        4.0      20240202     122533  185.832809        26.9    144748   

         loser_ht  loser_age  best_of  minutes  ...  l_1stWon  l_2ndWon  \
0      175.000000       20.6        3     63.0  ...      17.0       7.0   
1      188.000000       31.8        3     72.0  ...      22.0       6.0   
2      185.000000       21.6        3    101.0  ...      24.0      14.0   
3      173.000000       23.8        3    108.0  ...      38.0      15.0   
4      196.000000       20.6        3     65.0  ...      21.0      12.0   
...           ...        ...      ...      ...  ...       ...       ...   
89201  185.267928       18.8        3     81.0  ...      13.0       6.0   
89202  185.000000       23.9        3     95.0  ...      33.0       6.0   
89203  185.267928       21.8        3     77.0  ...      17.0       7.0   
89204  185.267928       23.2        3    131.0  ...      25.0       6.0   
89205  185.267928       27.3        3    159.0  ...      32.0      17.0   

       l_SvGms  l_bpSaved  l_bpFaced  winner_rank  winner_rank_points  \
0          8.0        2.0        6.0          9.0              1487.0   
1          8.0        7.0       11.0         94.0               371.0   
2         11.0        4.0        8.0         77.0               468.0   
3         13.0        8.0       12.0         65.0               502.0   
4          9.0        4.0        6.0        190.0               142.0   
...        ...        ...        ...          ...                 ...   
89201      8.0        0.0        6.0        136.0               489.0   
89202      8.0        6.0       11.0        136.0               489.0   
89203      6.0        8.0       14.0       1109.0                 8.0   
89204      9.0        1.0        4.0        554.0                67.0   
89205     14.0        5.0        9.0        554.0                67.0   

       loser_rank  loser_rank_points  sets  
0            78.0              459.0     2  
1           220.0              114.0     2  
2           212.0              116.0     3  
3            72.0              483.0     3  
4            28.0              876.0     2  
...           ...                ...   ...  
89201      1109.0                8.0     2  
89202       616.0               55.0     2  
89203       740.0               34.0     2  
89204       748.0               32.0     2  
89205       416.0              109.0     3  

[89206 rows x 33 columns]

In [373]:
df_num.isnull().sum()

draw_size             0
tourney_date          0
winner_id             0
winner_ht             0
winner_age            0
loser_id              0
loser_ht              0
loser_age             0
best_of               0
minutes               0
w_ace                 0
w_df                  0
w_svpt                0
w_1stIn               0
w_1stWon              0
w_2ndWon              0
w_SvGms               0
w_bpSaved             0
w_bpFaced             0
l_ace                 0
l_df                  0
l_svpt                0
l_1stIn               0
l_1stWon              0
l_2ndWon              0
l_SvGms               0
l_bpSaved             0
l_bpFaced             0
winner_rank           0
winner_rank_points    0
loser_rank            0
loser_rank_points     0
sets                  0
dtype: int64

In [374]:
#faltan los nulos de ranking que como no se pueden imputar por no ser real, BORRAR EN LA PARTE DE GENÉRICAS

# CATEGÓRICAS

In [375]:
    #df de variables categóricas
df_cat = df.drop(columns=df_num.columns)
df_cat

tourney_name surface tourney_level  \
0                          Auckland    Hard             A   
1                          Auckland    Hard             A   
2                          Auckland    Hard             A   
3                          Auckland    Hard             A   
4                          Auckland    Hard             A   
...                             ...     ...           ...   
89201  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89202  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89203  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89204  Davis Cup WG2 PO: VIE vs RSA    Hard             D   
89205  Davis Cup WG2 PO: VIE vs RSA    Hard             D   

                     winner_name winner_hand winner_ioc  \
0                 Emilio Sanchez           R        ESP   
1             Malivai Washington           R        USA   
2         Jean Philippe Fleurian           R        FRA   
3                     Eric Jelen           R        GER   
4                    Chuck Adams           R        USA   
...                          ...         ...        ...   
89201                 Radu Albot           R        MDA   
89202                 Radu Albot           R        MDA   
89203  Joaquin  Aguilar Cardozo            U        URU   
89204               Nam Hoang Ly           R        VIE   
89205               Nam Hoang Ly           R        VIE   

                      loser_name loser_hand loser_ioc        score round  
0                   Renzo Furlan          R       ITA      6-4 6-1   R32  
1                      Steve Guy          R       NZL      6-3 6-2   R32  
2                   Brett Steven          R       NZL  2-6 6-1 6-2   R32  
3                    Gilad Bloom          L       ISR  6-3 1-6 6-4   R32  
4               Richard Fromberg          R       AUS      6-3 6-4   R32  
...                          ...        ...       ...          ...   ...  
89201  Joaquin  Aguilar Cardozo           U       URU      6-2 6-3    RR  
89202          Franco Roncadelli          L       URU      6-3 6-1    RR  
89203               Ilya Snitari          U       MDA      6-1 6-0    RR  
89204             Philip Henning          R       RSA      6-3 6-4    RR  
89205               Kris Van Wyk          U       RSA  6-4 3-6 6-3    RR  

[89206 rows x 11 columns]

In [376]:
   df_cat.isnull().sum()

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       5
loser_ioc        0
score            0
round            0
dtype: int64

In [377]:
    # cuáles son los faltantes
df_cat[df_cat['loser_hand'].isna()]

tourney_name surface tourney_level  \
68595  Davis Cup G1 R1: CHI vs DOM    Clay             D   
68597  Davis Cup G1 R1: CHI vs DOM    Clay             D   
71022  Davis Cup G1 R1: DOM vs CHI    Hard             D   
73776  Davis Cup G2 R1: THA vs SRI    Clay             D   
73777  Davis Cup G2 R1: THA vs SRI    Clay             D   

                       winner_name winner_hand winner_ioc        loser_name  \
68595      Hans Podlipnik Castillo           R        CHI     Jose Olivares   
68597                 Gonzalo Lama           R        CHI     Jose Olivares   
71022           Tomas Barrios Vera           R        CHI     Jose Olivares   
73776  Wishaya Trongcharoenchaikul           R        THA  Yasitha De Silva   
73777        Jirat Navasirisomboon           R        THA  Yasitha De Silva   

      loser_hand loser_ioc           score round  
68595        NaN       DOM  6-1 6-1 7-6(4)    RR  
68597        NaN       DOM         6-4 6-0    RR  
71022        NaN       DOM   7-6(8) 7-6(2)    RR  
73776        NaN       SRI         6-3 6-3    RR  
73777        NaN       SRI         7-5 6-2    RR

In [378]:
players = pd.read_csv('atp_players.csv')

    # comprobación de si los nulos de loser_hand están en otro csv: players.csv
# 1º: Jose Olivares
players[(players['name_first']=='Jose') & (players['name_last']=='Olivares')]

player_id name_first name_last hand         dob  ioc  height  \
44757     144773       Jose  Olivares    R  19970108.0  DOM     NaN   

      wikidata_id  
44757   Q28674954

In [379]:
# 2º: Yasitha De Silva
players[(players['name_first']=='Yasitha') & (players['name_last']=='De Silva')]

player_id name_first name_last hand         dob  ioc  height  \
54565     202462    Yasitha  De Silva    R  19950703.0  SRI     NaN   

      wikidata_id  
54565         NaN

In [380]:
    #1er nan de loser_hand (para indices)
df_cat[df_cat['loser_name']=='Jose Olivares']

tourney_name surface tourney_level  \
68595  Davis Cup G1 R1: CHI vs DOM    Clay             D   
68597  Davis Cup G1 R1: CHI vs DOM    Clay             D   
71022  Davis Cup G1 R1: DOM vs CHI    Hard             D   

                   winner_name winner_hand winner_ioc     loser_name  \
68595  Hans Podlipnik Castillo           R        CHI  Jose Olivares   
68597             Gonzalo Lama           R        CHI  Jose Olivares   
71022       Tomas Barrios Vera           R        CHI  Jose Olivares   

      loser_hand loser_ioc           score round  
68595        NaN       DOM  6-1 6-1 7-6(4)    RR  
68597        NaN       DOM         6-4 6-0    RR  
71022        NaN       DOM   7-6(8) 7-6(2)    RR

In [381]:
    # imputar valor de loser_hand a los faltantes 
df_cat.loc[68595,'loser_hand']='R'
df_cat.loc[68597,'loser_hand']='R'
df_cat.loc[71022,'loser_hand']='R'
    # comprobar imputación
df_cat[df_cat['loser_name']=='Jose Olivares']

tourney_name surface tourney_level  \
68595  Davis Cup G1 R1: CHI vs DOM    Clay             D   
68597  Davis Cup G1 R1: CHI vs DOM    Clay             D   
71022  Davis Cup G1 R1: DOM vs CHI    Hard             D   

                   winner_name winner_hand winner_ioc     loser_name  \
68595  Hans Podlipnik Castillo           R        CHI  Jose Olivares   
68597             Gonzalo Lama           R        CHI  Jose Olivares   
71022       Tomas Barrios Vera           R        CHI  Jose Olivares   

      loser_hand loser_ioc           score round  
68595          R       DOM  6-1 6-1 7-6(4)    RR  
68597          R       DOM         6-4 6-0    RR  
71022          R       DOM   7-6(8) 7-6(2)    RR

In [382]:
    #siguiente nan de loser_hand (para indices)
df_cat[df_cat['loser_name']=='Yasitha De Silva']

tourney_name surface tourney_level  \
73776  Davis Cup G2 R1: THA vs SRI    Clay             D   
73777  Davis Cup G2 R1: THA vs SRI    Clay             D   

                       winner_name winner_hand winner_ioc        loser_name  \
73776  Wishaya Trongcharoenchaikul           R        THA  Yasitha De Silva   
73777        Jirat Navasirisomboon           R        THA  Yasitha De Silva   

      loser_hand loser_ioc    score round  
73776        NaN       SRI  6-3 6-3    RR  
73777        NaN       SRI  7-5 6-2    RR

In [383]:
    #imputaciñon de valores a loser_hand con nan
df_cat.loc[73776,'loser_hand']='R'
df_cat.loc[73777,'loser_hand']='R'
df_cat[df_cat['loser_name']=='Yasitha De Silva']

tourney_name surface tourney_level  \
73776  Davis Cup G2 R1: THA vs SRI    Clay             D   
73777  Davis Cup G2 R1: THA vs SRI    Clay             D   

                       winner_name winner_hand winner_ioc        loser_name  \
73776  Wishaya Trongcharoenchaikul           R        THA  Yasitha De Silva   
73777        Jirat Navasirisomboon           R        THA  Yasitha De Silva   

      loser_hand loser_ioc    score round  
73776          R       SRI  6-3 6-3    RR  
73777          R       SRI  7-5 6-2    RR

In [384]:
df_cat.isnull().sum() #limpio,sin nulos

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       0
loser_ioc        0
score            0
round            0
dtype: int64

In [385]:
df_cat.tourney_level.unique()

array(['A', 'G', 'M', 'F', 'D'], dtype=object)

## Limpieza de ROUND

In [386]:
   # limpiar round para que sea numerica 
df_cat['round'].unique()
# R32:32,R16:16,QF:8,SF:4,F:2,BR:128

array(['R32', 'R16', 'QF', 'SF', 'F', 'R128', 'R64', 'RR', 'ER', 'BR'],
      dtype=object)

In [387]:
df_cat['round'].value_counts()

round
R32     31713
R16     16849
R64     14713
R128     8960
QF       8441
SF       4324
F        2228
RR       1945
ER         32
BR          1
Name: count, dtype: int64

In [388]:
    # quitar la R a las rondas que tienen numero 
rondas = {'R32':32,'R16':16,'QF':8,'SF':4,'F':2,'R128':128,'R64':64,}
df_cat['round'] = df_cat['round'].map(rondas).fillna(df_cat['round'])
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR', 'ER', 'BR'],
      dtype=object)

In [389]:
    #ver donde están BR
df_cat[df_cat['round']=='BR']

tourney_name surface tourney_level    winner_name winner_hand  \
70096  Rio Olympics    Hard             A  Kei Nishikori           R   

      winner_ioc    loser_name loser_hand loser_ioc           score round  
70096        JPN  Rafael Nadal          L       ESP  6-2 6-7(1) 6-3    BR

In [390]:
    #ver cuantas rondas tiene Rio Olympics para saber que valor darle a BR
df[df['tourney_name']=='Rio Olympics'][['draw_size','round']].value_counts()

draw_size  round
64.0       R64      30
           R32      15
           R16       8
           QF        4
           SF        2
           BR        1
           F         1
Name: count, dtype: int64

In [391]:
    #buscar BR 
df_cat[(df_cat['tourney_name']=='Rio Olympics') & (df_cat['round']=='BR')]

tourney_name surface tourney_level    winner_name winner_hand  \
70096  Rio Olympics    Hard             A  Kei Nishikori           R   

      winner_ioc    loser_name loser_hand loser_ioc           score round  
70096        JPN  Rafael Nadal          L       ESP  6-2 6-7(1) 6-3    BR

In [392]:
   #imputar a BR=128
df_cat.loc[70096,'round']=128

    #comprobar imputación
df_cat[df_cat['tourney_name']=='Rio Olympics']['round'].value_counts()
df_cat[df_cat['tourney_name']=='Rio Olympics']['round'].unique()
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR', 'ER'], dtype=object)

In [393]:
    # Buscar donde estan ER
df_cat[df_cat['round']=='ER']

    # cuantos ER hay (32)
df_cat[df_cat['round']=='ER'].shape

    #que torneos tienen ER
df[df['round']=='ER']['tourney_name'].unique()

    #lista con los nombres de los torneos que tienen ER
RR_torneoER = list(df[df['round']=='ER']['tourney_name'].unique())
RR_torneoER

['Adelaide', 'Las Vegas', 'Delray Beach', 'Buenos Aires']

In [394]:
    # que rondas hay en cada uno de los 4 torneos con ER
df_cat[df_cat['tourney_name']=='Adelaide']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [395]:
df_cat[df_cat['tourney_name']=='Las Vegas']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [396]:
df_cat[df_cat['tourney_name']=='Delray Beach']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [397]:
df_cat[df_cat['tourney_name']=='Buenos Aires']['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 'ER', 'RR'], dtype=object)

In [398]:
    # lista los indices de las filas que contienen ER 
indices = list(df_cat[df_cat['round'] == 'ER'].index)
indices

[46605,
 46606,
 46607,
 46608,
 46609,
 46610,
 46611,
 46612,
 47531,
 47532,
 47533,
 47534,
 47535,
 47536,
 47537,
 47538,
 47802,
 47803,
 47804,
 47805,
 47806,
 47807,
 47808,
 47809,
 47869,
 47870,
 47871,
 47872,
 47873,
 47874,
 47875,
 47876]

In [399]:
   # cambiamos los ER=64
df_cat.loc[indices,'round'] = 64

    #comprobación de la imputación
df_cat['round'].unique()

array([32.0, 16.0, 8.0, 4.0, 2.0, 128.0, 64.0, 'RR'], dtype=object)

In [400]:
    # TORNEOS QUE TENIAN ER y RR
RR_torneoER

['Adelaide', 'Las Vegas', 'Delray Beach', 'Buenos Aires']

In [401]:
    # comprobación de como se sacarían los indices de uno
list(df_cat[(df_cat['tourney_name']=='Adelaide') & (df_cat['round']=='RR')].index)

[46613,
 46614,
 46615,
 46616,
 46617,
 46618,
 46619,
 46620,
 46621,
 46622,
 46623,
 46624,
 46625,
 46626,
 46627,
 46628,
 46629,
 46630,
 46631,
 46632,
 46633,
 46634,
 46635]

In [402]:
    # lista de listas de los indices de las filas con RR de los torneos que tenian ER y RR 
indices_RR = []
for i in RR_torneoER:
     indices_RR.append(list(df_cat[(df_cat['tourney_name']==i) & (df_cat['round']=='RR')].index))
len(indices_RR)

4

In [403]:
    #lista unica de indices_RR
import itertools
RR_indices = list(itertools.chain(*indices_RR))
len(RR_indices)

93

In [404]:
    # imputacion RR=128
df_cat.loc[RR_indices,'round'] =128

    #comprobación de la imputacion
for i in RR_torneoER:
     print(df_cat[df_cat['tourney_name']==i]['round'].unique())

[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]
[32.0 16.0 8.0 4.0 2.0 64 128]


In [405]:
    # Bucar los RR que faltan por imputar
df_cat[df_cat['round']=='RR']
df_cat[df_cat['round']=='RR']['tourney_name'].unique()  
# Faltan 'Tour Finals', 'Dusseldorf', 'Masters Cup', COPA DAVIS

array(['Tour Finals', 'Dusseldorf', 'Masters Cup',
       'Davis Cup G1 R1: BAR vs ECU', 'Davis Cup G1 R1: CHI vs DOM',
       'Davis Cup G1 R1: HUN vs ISR', 'Davis Cup G1 R1: NZL vs KOR',
       'Davis Cup G1 R1: PAK vs CHN', 'Davis Cup G1 R1: POR vs AUT',
       'Davis Cup G1 R1: ROU vs SLO', 'Davis Cup G1 R1: RUS vs SWE',
       'Davis Cup G2 R1: BIH vs TUN', 'Davis Cup G2 R1: BUL vs TUR',
       'Davis Cup G2 R1: EGY vs BLR', 'Davis Cup G2 R1: GEO vs DEN',
       'Davis Cup G2 R1: LTU vs NOR', 'Davis Cup G2 R1: MEX vs GUA',
       'Davis Cup G2 R1: MON vs LAT', 'Davis Cup G2 R1: PHI vs KUW',
       'Davis Cup G2 R1: RSA vs LUX', 'Davis Cup G2 R1: SRI vs THA',
       'Davis Cup G2 R1: VIE vs INA', 'Davis Cup G2 R1: ZIM vs FIN',
       'Davis Cup WG R1: ARG vs POL', 'Davis Cup WG R1: CAN vs FRA',
       'Davis Cup WG R1: CRO vs BEL', 'Davis Cup WG R1: GBR vs JPN',
       'Davis Cup WG R1: GER vs CZE', 'Davis Cup WG R1: SRB vs KAZ',
       'Davis Cup WG R1: SUI vs ITA', 'Davis Cup WG 

In [406]:
     # ver como es cada torneo menos la copa davis que va aparte
df_cat[df_cat['tourney_name']=='Tour Finals']['round'].unique()

array(['RR', 4.0, 2.0], dtype=object)

In [407]:
df_cat[df_cat['tourney_name']=='Dusseldorf']['round'].unique()

array(['RR', 2.0, 32.0, 16.0, 8.0, 4.0], dtype=object)

In [408]:
df_cat[df_cat['tourney_name']=='Masters Cup']['round'].unique()

array(['RR', 4.0, 2.0], dtype=object)

In [409]:
    # en Tour Finals y Master Cup RR = 8
indices = []
for i in ['Tour Finals','Masters Cup']:
      indices.append(list(df_cat[(df_cat['tourney_name']==i) & (df_cat['round']=='RR')].index))
RR_indices = list(itertools.chain(*indices))

    #imputacion RR=8
df_cat.loc[RR_indices,'round'] =8

    #comprobación de la imputación
for i in ['Tour Finals','Masters Cup']:
     print(df_cat[df_cat['tourney_name']==i]['round'].unique())

[8 4.0 2.0]
[8 4.0 2.0]


In [410]:
    # imputar RR=64 en 'Dusseldorf'
indices = list(df_cat[(df_cat['tourney_name']=='Dusseldorf') & (df_cat['round']=='RR')].index)

    # imputacion RR=64
df_cat.loc[indices,'round'] = 64

    # comprobacion de la imputacion
df_cat[df_cat['tourney_name']=='Dusseldorf']['round'].value_counts()

round
64      345
2.0      32
32.0     24
16.0     16
8.0       7
4.0       4
Name: count, dtype: int64

In [411]:
df_cat[df_cat['tourney_name']=='United Cup']['round'].unique()

array([2.0, 4.0, 'RR', 8.0], dtype=object)

In [412]:
    # imputacion RR en 'United Cup'
indices = list(df_cat[(df_cat['tourney_name']=='United Cup') & (df_cat['round']=='RR')].index)

    # imputacion RR=16
df_cat.loc[indices,'round'] = 16

    # comprobacion de la imputacion
df_cat[df_cat['tourney_name']=='United Cup']['round'].value_counts()

round
16     53
4.0     6
8.0     4
2.0     2
Name: count, dtype: int64

In [413]:
    # RR que faltan por imputar (copa davis)
df_cat[df_cat['round']=='RR']['tourney_name'].unique()

array(['Davis Cup G1 R1: BAR vs ECU', 'Davis Cup G1 R1: CHI vs DOM',
       'Davis Cup G1 R1: HUN vs ISR', 'Davis Cup G1 R1: NZL vs KOR',
       'Davis Cup G1 R1: PAK vs CHN', 'Davis Cup G1 R1: POR vs AUT',
       'Davis Cup G1 R1: ROU vs SLO', 'Davis Cup G1 R1: RUS vs SWE',
       'Davis Cup G2 R1: BIH vs TUN', 'Davis Cup G2 R1: BUL vs TUR',
       'Davis Cup G2 R1: EGY vs BLR', 'Davis Cup G2 R1: GEO vs DEN',
       'Davis Cup G2 R1: LTU vs NOR', 'Davis Cup G2 R1: MEX vs GUA',
       'Davis Cup G2 R1: MON vs LAT', 'Davis Cup G2 R1: PHI vs KUW',
       'Davis Cup G2 R1: RSA vs LUX', 'Davis Cup G2 R1: SRI vs THA',
       'Davis Cup G2 R1: VIE vs INA', 'Davis Cup G2 R1: ZIM vs FIN',
       'Davis Cup WG R1: ARG vs POL', 'Davis Cup WG R1: CAN vs FRA',
       'Davis Cup WG R1: CRO vs BEL', 'Davis Cup WG R1: GBR vs JPN',
       'Davis Cup WG R1: GER vs CZE', 'Davis Cup WG R1: SRB vs KAZ',
       'Davis Cup WG R1: SUI vs ITA', 'Davis Cup WG R1: USA vs AUS',
       'Davis Cup G1 R2: BRA vs EC

In [414]:
    # comprobacion si ronda en el nombre == round (#no son iguales)
df_cat[df_cat['tourney_name']=='Davis Cup G1 R1: BAR vs ECU']

tourney_name surface tourney_level  winner_name  \
68594  Davis Cup G1 R1: BAR vs ECU    Clay             D  Ivan Endara   

      winner_hand winner_ioc   loser_name loser_hand loser_ioc        score  \
68594           R        ECU  Darian King          R       BAR  6-1 6-2 6-4   

      round  
68594    RR

In [415]:
df[df['tourney_name'].str.startswith('Davis')]

tourney_name surface  draw_size tourney_level  \
68594   Davis Cup G1 R1: BAR vs ECU    Clay        4.0             D   
68595   Davis Cup G1 R1: CHI vs DOM    Clay        4.0             D   
68596   Davis Cup G1 R1: CHI vs DOM    Clay        4.0             D   
68597   Davis Cup G1 R1: CHI vs DOM    Clay        4.0             D   
68598   Davis Cup G1 R1: HUN vs ISR    Clay        4.0             D   
...                             ...     ...        ...           ...   
89201  Davis Cup WG2 PO: URU vs MDA    Clay        4.0             D   
89202  Davis Cup WG2 PO: URU vs MDA    Clay        4.0             D   
89203  Davis Cup WG2 PO: URU vs MDA    Clay        4.0             D   
89204  Davis Cup WG2 PO: VIE vs RSA    Hard        4.0             D   
89205  Davis Cup WG2 PO: VIE vs RSA    Hard        4.0             D   

       tourney_date  winner_id                winner_name winner_hand  \
68594      20160304     105111                Ivan Endara           R   
68595      20160304     105070    Hans Podlipnik Castillo           R   
68596      20160304     106174               Gonzalo Lama           R   
68597      20160304     106174               Gonzalo Lama           R   
68598      20160304     105954                 Peter Nagy           R   
...             ...        ...                        ...         ...   
89201      20240203     105430                 Radu Albot           R   
89202      20240203     105430                 Radu Albot           R   
89203      20240203     212051  Joaquin  Aguilar Cardozo            U   
89204      20240202     122533               Nam Hoang Ly           R   
89205      20240202     122533               Nam Hoang Ly           R   

       winner_ht winner_ioc  ...  l_1stWon  l_2ndWon l_SvGms l_bpSaved  \
68594        NaN        ECU  ...      29.0      11.0    12.0       6.0   
68595      183.0        CHI  ...      37.0      14.0    13.0      10.0   
68596      180.0        CHI  ...      55.0      10.0    16.0       5.0   
68597      180.0        CHI  ...      17.0       9.0     8.0       2.0   
68598      180.0        HUN  ...      41.0      23.0    22.0       8.0   
...          ...        ...  ...       ...       ...     ...       ...   
89201      175.0        MDA  ...      13.0       6.0     8.0       0.0   
89202      175.0        MDA  ...      33.0       6.0     8.0       6.0   
89203        NaN        URU  ...      17.0       7.0     6.0       8.0   
89204        NaN        VIE  ...      25.0       6.0     9.0       1.0   
89205        NaN        VIE  ...      32.0      17.0    14.0       5.0   

       l_bpFaced winner_rank  winner_rank_points loser_rank  \
68594       13.0       395.0               108.0      243.0   
68595       16.0       198.0               267.0     1250.0   
68596        8.0       263.0               199.0      222.0   
68597        6.0       263.0               199.0     1250.0   
68598       19.0       612.0                50.0       89.0   
...          ...         ...                 ...        ...   
89201        6.0       136.0               489.0     1109.0   
89202       11.0       136.0               489.0      616.0   
89203       14.0      1109.0                 8.0      740.0   
89204        4.0       554.0                67.0      748.0   
89205        9.0       554.0                67.0      416.0   

       loser_rank_points sets  
68594              217.0    3  
68595                6.0    3  
68596              234.0    3  
68597                6.0    2  
68598              613.0    5  
...                  ...  ...  
89201                8.0    2  
89202               55.0    2  
89203               34.0    2  
89204               32.0    2  
89205              109.0    3  

[955 rows x 44 columns]

In [416]:
lista=[]
for i in df_cat[df_cat['tourney_name'].str.startswith('Davis')]['tourney_name']:
    c = re.findall(r'(\w{1,2}):', i)
    lista.append(c)
lista

[['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R1'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 ['R2'],
 

In [417]:
    # lista con los indices de las filas a cambiar round por ronda en el nombre 
filtro = list(df_cat[df_cat['tourney_name'].str.startswith('Davis')].index)

    # imputacion de las rondas en los nombres a los valores de 'round'
df_cat.loc[filtro, 'round'] = lista


In [418]:
    # valores unicos de las variables (round ahora con nuevos alfanumericos por la copa davis)
for i in ['surface', 'tourney_level','winner_hand','loser_hand','round']:
     print(df_cat[i].unique())

['Hard' 'Carpet' 'Clay' 'Grass']
['A' 'G' 'M' 'F' 'D']
['R' 'L' 'A' 'U']
['R' 'L' 'U' 'A']
[32.0 16.0 8.0 4.0 2.0 128.0 64.0 'R1' 'R2' 'QF' 'R3' 'PO' 'SF' 'F' 'RR']


In [419]:
    # nuevo diccionario para imputar valores con alfanumericos en round del torneo Copa Davis
{'F':2,'SF':4,'QF':8,'R3':16,'R2':32,'R1':64,'PO':128,'RR':256}

{'F': 2, 'SF': 4, 'QF': 8, 'R3': 16, 'R2': 32, 'R1': 64, 'PO': 128, 'RR': 256}

In [420]:
# rondas quitar la R a las que tienen numero 
rondas = {'F':2,'SF':4,'QF':8,'R3':16,'R2':32,'R1':64,'PO':128,'RR':256}
df_cat['round'] = df_cat['round'].map(rondas).fillna(df_cat['round'])

In [421]:
for i in ['surface', 'tourney_level','winner_hand','loser_hand','round']:
    print(df_cat[i].unique())

['Hard' 'Carpet' 'Clay' 'Grass']
['A' 'G' 'M' 'F' 'D']
['R' 'L' 'A' 'U']
['R' 'L' 'U' 'A']
[ 32.  16.   8.   4.   2. 128.  64. 256.]


In [422]:
df_cat

tourney_name surface tourney_level  \
0                          Auckland    Hard             A   
1                          Auckland    Hard             A   
2                          Auckland    Hard             A   
3                          Auckland    Hard             A   
4                          Auckland    Hard             A   
...                             ...     ...           ...   
89201  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89202  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89203  Davis Cup WG2 PO: URU vs MDA    Clay             D   
89204  Davis Cup WG2 PO: VIE vs RSA    Hard             D   
89205  Davis Cup WG2 PO: VIE vs RSA    Hard             D   

                     winner_name winner_hand winner_ioc  \
0                 Emilio Sanchez           R        ESP   
1             Malivai Washington           R        USA   
2         Jean Philippe Fleurian           R        FRA   
3                     Eric Jelen           R        GER   
4                    Chuck Adams           R        USA   
...                          ...         ...        ...   
89201                 Radu Albot           R        MDA   
89202                 Radu Albot           R        MDA   
89203  Joaquin  Aguilar Cardozo            U        URU   
89204               Nam Hoang Ly           R        VIE   
89205               Nam Hoang Ly           R        VIE   

                      loser_name loser_hand loser_ioc        score  round  
0                   Renzo Furlan          R       ITA      6-4 6-1   32.0  
1                      Steve Guy          R       NZL      6-3 6-2   32.0  
2                   Brett Steven          R       NZL  2-6 6-1 6-2   32.0  
3                    Gilad Bloom          L       ISR  6-3 1-6 6-4   32.0  
4               Richard Fromberg          R       AUS      6-3 6-4   32.0  
...                          ...        ...       ...          ...    ...  
89201  Joaquin  Aguilar Cardozo           U       URU      6-2 6-3  128.0  
89202          Franco Roncadelli          L       URU      6-3 6-1  128.0  
89203               Ilya Snitari          U       MDA      6-1 6-0  128.0  
89204             Philip Henning          R       RSA      6-3 6-4  128.0  
89205               Kris Van Wyk          U       RSA  6-4 3-6 6-3  128.0  

[89206 rows x 11 columns]

In [423]:
df_cat.isnull().sum()

tourney_name     0
surface          0
tourney_level    0
winner_name      0
winner_hand      0
winner_ioc       0
loser_name       0
loser_hand       0
loser_ioc        0
score            0
round            0
dtype: int64

# LIMPIO_FINAL

In [424]:
df2 = pd.concat([df_num, df_cat], axis=1)
df2

draw_size  tourney_date  winner_id   winner_ht  winner_age  loser_id  \
0           32.0      19910107     101142  180.000000        25.6    101746   
1           32.0      19910107     101613  180.000000        21.5    100587   
2           32.0      19910107     101179  185.000000        25.3    101601   
3           32.0      19910107     101117  180.000000        25.8    101332   
4           32.0      19910107     101901  185.000000        19.7    101735   
...          ...           ...        ...         ...         ...       ...   
89201        4.0      20240203     105430  175.000000        34.2    212051   
89202        4.0      20240203     105430  175.000000        34.2    208364   
89203        4.0      20240203     212051  185.832809        18.8    209943   
89204        4.0      20240202     122533  185.832809        26.9    202475   
89205        4.0      20240202     122533  185.832809        26.9    144748   

         loser_ht  loser_age  best_of  minutes  ...  surface  tourney_level  \
0      175.000000       20.6        3     63.0  ...     Hard              A   
1      188.000000       31.8        3     72.0  ...     Hard              A   
2      185.000000       21.6        3    101.0  ...     Hard              A   
3      173.000000       23.8        3    108.0  ...     Hard              A   
4      196.000000       20.6        3     65.0  ...     Hard              A   
...           ...        ...      ...      ...  ...      ...            ...   
89201  185.267928       18.8        3     81.0  ...     Clay              D   
89202  185.000000       23.9        3     95.0  ...     Clay              D   
89203  185.267928       21.8        3     77.0  ...     Clay              D   
89204  185.267928       23.2        3    131.0  ...     Hard              D   
89205  185.267928       27.3        3    159.0  ...     Hard              D   

                     winner_name  winner_hand  winner_ioc  \
0                 Emilio Sanchez            R         ESP   
1             Malivai Washington            R         USA   
2         Jean Philippe Fleurian            R         FRA   
3                     Eric Jelen            R         GER   
4                    Chuck Adams            R         USA   
...                          ...          ...         ...   
89201                 Radu Albot            R         MDA   
89202                 Radu Albot            R         MDA   
89203  Joaquin  Aguilar Cardozo             U         URU   
89204               Nam Hoang Ly            R         VIE   
89205               Nam Hoang Ly            R         VIE   

                      loser_name  loser_hand  loser_ioc        score  round  
0                   Renzo Furlan           R        ITA      6-4 6-1   32.0  
1                      Steve Guy           R        NZL      6-3 6-2   32.0  
2                   Brett Steven           R        NZL  2-6 6-1 6-2   32.0  
3                    Gilad Bloom           L        ISR  6-3 1-6 6-4   32.0  
4               Richard Fromberg           R        AUS      6-3 6-4   32.0  
...                          ...         ...        ...          ...    ...  
89201  Joaquin  Aguilar Cardozo            U        URU      6-2 6-3  128.0  
89202          Franco Roncadelli           L        URU      6-3 6-1  128.0  
89203               Ilya Snitari           U        MDA      6-1 6-0  128.0  
89204             Philip Henning           R        RSA      6-3 6-4  128.0  
89205               Kris Van Wyk           U        RSA  6-4 3-6 6-3  128.0  

[89206 rows x 44 columns]

In [425]:
df2.isnull().sum()

draw_size             0
tourney_date          0
winner_id             0
winner_ht             0
winner_age            0
loser_id              0
loser_ht              0
loser_age             0
best_of               0
minutes               0
w_ace                 0
w_df                  0
w_svpt                0
w_1stIn               0
w_1stWon              0
w_2ndWon              0
w_SvGms               0
w_bpSaved             0
w_bpFaced             0
l_ace                 0
l_df                  0
l_svpt                0
l_1stIn               0
l_1stWon              0
l_2ndWon              0
l_SvGms               0
l_bpSaved             0
l_bpFaced             0
winner_rank           0
winner_rank_points    0
loser_rank            0
loser_rank_points     0
sets                  0
tourney_name          0
surface               0
tourney_level         0
winner_name           0
winner_hand           0
winner_ioc            0
loser_name            0
loser_hand            0
loser_ioc       

In [428]:
df2.to_csv('limpio_final.csv',index=False)